ApiUrl="https://api2.supergreenlab.com"
StorageUrl="https://storage.supergreenlab.com"
StorageHost="storage.supergreenlab.com"
LevelDBDir="/var/liveserver/sgllive.leveldb"
StorageDir="/var/liveserver/storage"
