ApiUrl="http://api2.supergreenlab.com"
MotionUrl="http://localhost:8082"
StorageUrl="http://storage.supergreenlab.com"
StorageHost="storage.supergreenlab.com"
LevelDBDir="/var/liveserver/sgllive.leveldb"
